# Generated by Django 5.0.3 on 2026-02-02 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('type', models.CharField(db_index=True, max_length=80)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='others', to='campaigns.campaign')),
            ],
            options={
                'db_table': 'other',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OtherCampaignType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_links', to='campaigns.campaigntype')),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_types', to='others.other')),
            ],
            options={
                'db_table': 'other_campaign_type',
            },
        ),
        migrations.AddConstraint(
            model_name='othercampaigntype',
            constraint=models.UniqueConstraint(fields=('campaign_type', 'other'), name='unique_other_campaign_type'),
        ),
    ]
