# Generated by Django 5.0.3 on 2026-02-20 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0002_campaignsettings_level_thresholds'),
        ('warbands', '0008_allow_duplicate_skills_spells'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('inviting', 'Inviting'), ('prebattle', 'Prebattle'), ('active', 'Active'), ('postbattle', 'Postbattle'), ('ended', 'Ended'), ('canceled', 'Canceled')], default='inviting', max_length=20)),
                ('settings_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('post_processed_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='campaigns.campaign')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_created', to=settings.AUTH_USER_MODEL)),
                ('winner_warband', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles_won', to='warbands.warband')),
            ],
            options={
                'db_table': 'battle',
            },
        ),
        migrations.CreateModel(
            name='BattleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('battle_created', 'Battle created'), ('participant_invited', 'Participant invited'), ('participant_joined_prebattle', 'Participant joined prebattle'), ('participant_ready_set', 'Participant ready set'), ('participant_ready_unset', 'Participant ready unset'), ('participant_canceled_prebattle', 'Participant canceled prebattle'), ('participant_rejoined', 'Participant rejoined'), ('battle_started', 'Battle started'), ('participant_joined_battle', 'Participant joined battle'), ('kill_recorded', 'Kill recorded'), ('death_recorded', 'Death recorded'), ('item_used', 'Item used'), ('participant_finished_battle', 'Participant finished battle'), ('battle_entered_postbattle', 'Battle entered postbattle'), ('winner_declared', 'Winner declared'), ('participant_confirmed_postbattle', 'Participant confirmed postbattle'), ('battle_ended', 'Battle ended'), ('battle_canceled', 'Battle canceled')], max_length=64)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_events', to=settings.AUTH_USER_MODEL)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='battles.battle')),
            ],
            options={
                'db_table': 'battle_event',
            },
        ),
        migrations.CreateModel(
            name='BattleParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('joined_prebattle', 'Joined prebattle'), ('ready', 'Ready'), ('canceled_prebattle', 'Canceled prebattle'), ('in_battle', 'In battle'), ('finished_battle', 'Finished battle'), ('confirmed_postbattle', 'Confirmed postbattle')], default='invited', max_length=30)),
                ('connection_state', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=10)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('battle_joined_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_event_id', models.BigIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='battles.battle')),
                ('invited_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_participant_invites', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_participations', to=settings.AUTH_USER_MODEL)),
                ('warband', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_participations', to='warbands.warband')),
            ],
            options={
                'db_table': 'battle_participant',
            },
        ),
        migrations.AddIndex(
            model_name='battle',
            index=models.Index(fields=['campaign', 'status'], name='battle_campaig_5ab1d4_idx'),
        ),
        migrations.AddIndex(
            model_name='battle',
            index=models.Index(fields=['status', 'created_at'], name='battle_status_eaee00_idx'),
        ),
        migrations.AddIndex(
            model_name='battleevent',
            index=models.Index(fields=['battle', 'id'], name='battle_even_battle__e35349_idx'),
        ),
        migrations.AddIndex(
            model_name='battleevent',
            index=models.Index(fields=['battle', 'type'], name='battle_even_battle__3d5b67_idx'),
        ),
        migrations.AddIndex(
            model_name='battleparticipant',
            index=models.Index(fields=['battle', 'status'], name='battle_part_battle__fb028c_idx'),
        ),
        migrations.AddIndex(
            model_name='battleparticipant',
            index=models.Index(fields=['user', 'status'], name='battle_part_user_id_a11c22_idx'),
        ),
        migrations.AddConstraint(
            model_name='battleparticipant',
            constraint=models.UniqueConstraint(fields=('battle', 'user'), name='unique_battle_participant_user'),
        ),
        migrations.AddConstraint(
            model_name='battleparticipant',
            constraint=models.UniqueConstraint(fields=('battle', 'warband'), name='unique_battle_participant_warband'),
        ),
    ]
