# Generated by Django 5.0.3 on 2026-02-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="battle",
            name="scenario",
            field=models.CharField(default="Unknown Scenario", max_length=120),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="battle",
            constraint=models.CheckConstraint(
                check=~models.Q(scenario=""),
                name="battle_scenario_not_empty",
            ),
        ),
    ]
