# Generated by Django 5.0.3 on 2026-02-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0002_battle_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='title',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='battleparticipant',
            name='declared_rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battleparticipant',
            name='selected_unit_keys_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='battleparticipant',
            name='stat_overrides_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='battleevent',
            name='type',
            field=models.CharField(choices=[('battle_created', 'Battle created'), ('participant_invited', 'Participant invited'), ('participant_accepted', 'Participant accepted'), ('participant_joined_prebattle', 'Participant joined prebattle'), ('participant_ready_set', 'Participant ready set'), ('participant_ready_unset', 'Participant ready unset'), ('participant_canceled_prebattle', 'Participant canceled prebattle'), ('participant_rejoined', 'Participant rejoined'), ('battle_started', 'Battle started'), ('battle_prebattle_opened', 'Battle prebattle opened'), ('participant_joined_battle', 'Participant joined battle'), ('kill_recorded', 'Kill recorded'), ('death_recorded', 'Death recorded'), ('item_used', 'Item used'), ('participant_finished_battle', 'Participant finished battle'), ('battle_entered_postbattle', 'Battle entered postbattle'), ('winner_declared', 'Winner declared'), ('participant_confirmed_postbattle', 'Participant confirmed postbattle'), ('battle_ended', 'Battle ended'), ('battle_canceled', 'Battle canceled')], max_length=64),
        ),
        migrations.AlterField(
            model_name='battleparticipant',
            name='status',
            field=models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('joined_prebattle', 'Joined prebattle'), ('ready', 'Ready'), ('canceled_prebattle', 'Canceled prebattle'), ('in_battle', 'In battle'), ('finished_battle', 'Finished battle'), ('confirmed_postbattle', 'Confirmed postbattle')], default='invited', max_length=30),
        ),
    ]
