# Generated by Django 5.0.3 on 2026-02-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battles", "0004_battleparticipant_custom_units_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="battleparticipant",
            name="unit_information_json",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
