# Generated by Django 5.0.3 on 2026-03-23 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("battles", "0009_battle_flow_type_and_reported_result_statuses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="battle",
            name="title",
        ),
    ]
