from django.urls import path

from .views import (
    HeroSpecialDetailView,
    HeroSpellDetailView,
    WarbandDetailView,
    WarbandHenchmenGroupDetailView,
    WarbandHenchmenGroupLevelUpView,
    WarbandHenchmenGroupListCreateView,
    WarbandHeroDetailView,
    WarbandHeroLevelUpView,
    WarbandHeroDetailListView,
    WarbandHeroListCreateView,
    WarbandItemDetailView,
    WarbandItemListView,
    WarbandListCreateView,
    WarbandLogListView,
    WarbandResourceDetailView,
    WarbandResourceListCreateView,
    WarbandSummaryView,
    WarbandTradeListCreateView,
)

urlpatterns = [
    path("warbands/", WarbandListCreateView.as_view(), name="warbands"),
    path("warbands/<int:warband_id>/", WarbandDetailView.as_view(), name="warbands-detail"),
    path(
        "warbands/<int:warband_id>/summary/",
        WarbandSummaryView.as_view(),
        name="warbands-summary",
    ),
    path(
        "warbands/<int:warband_id>/items/",
        WarbandItemListView.as_view(),
        name="warbands-items",
    ),
    path(
        "warbands/<int:warband_id>/items/<int:item_id>/",
        WarbandItemDetailView.as_view(),
        name="warbands-items-detail",
    ),
    path(
        "warbands/<int:warband_id>/heroes/",
        WarbandHeroListCreateView.as_view(),
        name="warbands-heroes",
    ),
    path(
        "warbands/<int:warband_id>/heroes/detail/",
        WarbandHeroDetailListView.as_view(),
        name="warbands-heroes-detail-list",
    ),
    path(
        "warbands/<int:warband_id>/heroes/<int:hero_id>/",
        WarbandHeroDetailView.as_view(),
        name="warbands-heroes-detail",
    ),
    path(
        "warbands/<int:warband_id>/heroes/<int:hero_id>/level-up/",
        WarbandHeroLevelUpView.as_view(),
        name="warbands-heroes-level-up",
    ),
    path(
        "warbands/hero-specials/<int:special_id>/",
        HeroSpecialDetailView.as_view(),
        name="warbands-hero-special-detail",
    ),
    path(
        "warbands/hero-spells/<int:spell_id>/",
        HeroSpellDetailView.as_view(),
        name="warbands-hero-spell-detail",
    ),
    path(
        "warbands/<int:warband_id>/henchmen-groups/",
        WarbandHenchmenGroupListCreateView.as_view(),
        name="warbands-henchmen-groups",
    ),
    path(
        "warbands/<int:warband_id>/henchmen-groups/<int:group_id>/",
        WarbandHenchmenGroupDetailView.as_view(),
        name="warbands-henchmen-groups-detail",
    ),
    path(
        "warbands/<int:warband_id>/henchmen-groups/<int:group_id>/level-up/",
        WarbandHenchmenGroupLevelUpView.as_view(),
        name="warbands-henchmen-groups-level-up",
    ),
    path(
        "warbands/<int:warband_id>/logs/",
        WarbandLogListView.as_view(),
        name="warbands-logs",
    ),
    path(
        "warbands/<int:warband_id>/resources/",
        WarbandResourceListCreateView.as_view(),
        name="warbands-resources",
    ),
    path(
        "warbands/<int:warband_id>/resources/<int:resource_id>/",
        WarbandResourceDetailView.as_view(),
        name="warbands-resources-detail",
    ),
    path(
        "warbands/<int:warband_id>/trades/",
        WarbandTradeListCreateView.as_view(),
        name="warbands-trades",
    ),
]
