# Generated by Django 5.0.3 on 2026-01-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warbands', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='henchmengroup',
            name='kills',
        ),
        migrations.AddField(
            model_name='hiredsword',
            name='kills',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
