# Generated by Django 5.0.3 on 2026-02-01 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warbands', '0002_warband_dice_color'),
        ('warbands', '0004_spell_tables_and_feature_rename'),
    ]

    operations = [
    ]

