# Generated by Codex on 2026-02-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("others", "0001_initial"),
        ("spells", "0001_initial"),
        ("warbands", "0005_merge_20260201_1816"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HeroSpell",
        ),
        migrations.DeleteModel(
            name="HiredSwordSpell",
        ),
        migrations.DeleteModel(
            name="HeroOther",
        ),
        migrations.DeleteModel(
            name="HenchmenGroupOther",
        ),
        migrations.DeleteModel(
            name="HiredSwordOther",
        ),
        migrations.CreateModel(
            name="HeroOther",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("hero", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="hero_others", to="warbands.hero")),
                ("other", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="hero_others", to="others.other")),
            ],
            options={
                "db_table": "hero_other",
            },
        ),
        migrations.CreateModel(
            name="HenchmenGroupOther",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("henchmen_group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="henchmen_group_others", to="warbands.henchmengroup")),
                ("other", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="henchmen_group_others", to="others.other")),
            ],
            options={
                "db_table": "henchmen_group_other",
            },
        ),
        migrations.CreateModel(
            name="HiredSwordOther",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("hired_sword", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="hired_sword_others", to="warbands.hiredsword")),
                ("other", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="hired_sword_others", to="others.other")),
            ],
            options={
                "db_table": "hired_sword_other",
            },
        ),
        migrations.CreateModel(
            name="HeroSpell",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("hero", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="hero_spells", to="warbands.hero")),
                ("spell", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="hero_spells", to="spells.spell")),
            ],
            options={
                "db_table": "hero_spell",
            },
        ),
        migrations.CreateModel(
            name="HenchmenGroupSpell",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("henchmen_group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="henchmen_group_spells", to="warbands.henchmengroup")),
                ("spell", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="henchmen_group_spells", to="spells.spell")),
            ],
            options={
                "db_table": "henchmen_group_spell",
            },
        ),
        migrations.CreateModel(
            name="HiredSwordSpell",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("hired_sword", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="hired_sword_spells", to="warbands.hiredsword")),
                ("spell", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="hired_sword_spells", to="spells.spell")),
            ],
            options={
                "db_table": "hired_sword_spell",
            },
        ),
        migrations.AddField(
            model_name="hero",
            name="others",
            field=models.ManyToManyField(blank=True, related_name="heroes", through="warbands.HeroOther", to="others.other"),
        ),
        migrations.AddField(
            model_name="hero",
            name="spells",
            field=models.ManyToManyField(blank=True, related_name="heroes", through="warbands.HeroSpell", to="spells.spell"),
        ),
        migrations.AddField(
            model_name="henchmengroup",
            name="others",
            field=models.ManyToManyField(blank=True, related_name="henchmen_groups", through="warbands.HenchmenGroupOther", to="others.other"),
        ),
        migrations.AddField(
            model_name="henchmengroup",
            name="spells",
            field=models.ManyToManyField(blank=True, related_name="henchmen_groups", through="warbands.HenchmenGroupSpell", to="spells.spell"),
        ),
        migrations.AddField(
            model_name="hiredsword",
            name="others",
            field=models.ManyToManyField(blank=True, related_name="hired_swords", through="warbands.HiredSwordOther", to="others.other"),
        ),
        migrations.AddField(
            model_name="hiredsword",
            name="spells",
            field=models.ManyToManyField(blank=True, related_name="hired_swords", through="warbands.HiredSwordSpell", to="spells.spell"),
        ),
        migrations.AddConstraint(
            model_name="heroother",
            constraint=models.UniqueConstraint(fields=("hero", "other"), name="unique_hero_other"),
        ),
        migrations.AddConstraint(
            model_name="henchmengroupother",
            constraint=models.UniqueConstraint(fields=("henchmen_group", "other"), name="unique_henchmen_group_other"),
        ),
        migrations.AddConstraint(
            model_name="hiredswordother",
            constraint=models.UniqueConstraint(fields=("hired_sword", "other"), name="unique_hired_sword_other"),
        ),
        migrations.AddConstraint(
            model_name="herospell",
            constraint=models.UniqueConstraint(fields=("hero", "spell"), name="unique_hero_spell"),
        ),
        migrations.AddConstraint(
            model_name="henchmengroupspell",
            constraint=models.UniqueConstraint(fields=("henchmen_group", "spell"), name="unique_henchmen_group_spell"),
        ),
        migrations.AddConstraint(
            model_name="hiredswordspell",
            constraint=models.UniqueConstraint(fields=("hired_sword", "spell"), name="unique_hired_sword_spell"),
        ),
    ]
