# Generated by Codex on 2026-02-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0001_initial"),
        ("spells", "0001_initial"),
        ("warbands", "0005_merge_20260201_1816"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HeroSpell",
        ),
        migrations.DeleteModel(
            name="HiredSwordSpell",
        ),
        migrations.DeleteModel(
            name="HeroFeature",
        ),
        migrations.DeleteModel(
            name="HenchmenGroupFeature",
        ),
        migrations.DeleteModel(
            name="HiredSwordFeature",
        ),
        migrations.CreateModel(
            name="HeroFeature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("hero", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="hero_features", to="warbands.hero")),
                ("feature", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="hero_features", to="features.feature")),
            ],
            options={
                "db_table": "hero_feature",
            },
        ),
        migrations.CreateModel(
            name="HenchmenGroupFeature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("henchmen_group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="henchmen_group_features", to="warbands.henchmengroup")),
                ("feature", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="henchmen_group_features", to="features.feature")),
            ],
            options={
                "db_table": "henchmen_group_feature",
            },
        ),
        migrations.CreateModel(
            name="HiredSwordFeature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("hired_sword", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="hired_sword_features", to="warbands.hiredsword")),
                ("feature", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="hired_sword_features", to="features.feature")),
            ],
            options={
                "db_table": "hired_sword_feature",
            },
        ),
        migrations.CreateModel(
            name="HeroSpell",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("hero", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="hero_spells", to="warbands.hero")),
                ("spell", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="hero_spells", to="spells.spell")),
            ],
            options={
                "db_table": "hero_spell",
            },
        ),
        migrations.CreateModel(
            name="HenchmenGroupSpell",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("henchmen_group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="henchmen_group_spells", to="warbands.henchmengroup")),
                ("spell", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="henchmen_group_spells", to="spells.spell")),
            ],
            options={
                "db_table": "henchmen_group_spell",
            },
        ),
        migrations.CreateModel(
            name="HiredSwordSpell",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("hired_sword", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="hired_sword_spells", to="warbands.hiredsword")),
                ("spell", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="hired_sword_spells", to="spells.spell")),
            ],
            options={
                "db_table": "hired_sword_spell",
            },
        ),
        migrations.AddField(
            model_name="hero",
            name="features",
            field=models.ManyToManyField(blank=True, related_name="heroes", through="warbands.HeroFeature", to="features.feature"),
        ),
        migrations.AddField(
            model_name="hero",
            name="spells",
            field=models.ManyToManyField(blank=True, related_name="heroes", through="warbands.HeroSpell", to="spells.spell"),
        ),
        migrations.AddField(
            model_name="henchmengroup",
            name="features",
            field=models.ManyToManyField(blank=True, related_name="henchmen_groups", through="warbands.HenchmenGroupFeature", to="features.feature"),
        ),
        migrations.AddField(
            model_name="henchmengroup",
            name="spells",
            field=models.ManyToManyField(blank=True, related_name="henchmen_groups", through="warbands.HenchmenGroupSpell", to="spells.spell"),
        ),
        migrations.AddField(
            model_name="hiredsword",
            name="features",
            field=models.ManyToManyField(blank=True, related_name="hired_swords", through="warbands.HiredSwordFeature", to="features.feature"),
        ),
        migrations.AddField(
            model_name="hiredsword",
            name="spells",
            field=models.ManyToManyField(blank=True, related_name="hired_swords", through="warbands.HiredSwordSpell", to="spells.spell"),
        ),
        migrations.AddConstraint(
            model_name="herospell",
            constraint=models.UniqueConstraint(fields=("hero", "spell"), name="unique_hero_spell"),
        ),
        migrations.AddConstraint(
            model_name="henchmengroupspell",
            constraint=models.UniqueConstraint(fields=("henchmen_group", "spell"), name="unique_henchmen_group_spell"),
        ),
        migrations.AddConstraint(
            model_name="hiredswordspell",
            constraint=models.UniqueConstraint(fields=("hired_sword", "spell"), name="unique_hired_sword_spell"),
        ),
    ]

