# Generated by Django 5.0.3 on 2026-02-04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warbands", "0006_spells_features_pivots"),
    ]

    operations = [
        # caster field moved to 0001_initial
    ]
