# Generated by Django 5.0.3 on 2026-02-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warbands", "0006_spells_features_pivots"),
    ]

    operations = [
        migrations.AddField(
            model_name="hero",
            name="wizard",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hiredsword",
            name="wizard",
            field=models.BooleanField(default=False),
        ),
    ]
