# Generated by Django 5.0.3 on 2026-02-07 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warbands', '0002_warbanditem_quantity'),
        ('warbands', '0008_warbandtrade'),
    ]

    operations = [
    ]
