# Generated by Django 5.0.3 on 2026-02-25 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warbands', '0010_warband_restrictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='warbandlog',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='warbands.warbandlog'),
        ),
        migrations.AddField(
            model_name='warbandtrade',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='warbands.warbandtrade'),
        ),
    ]
