# Generated by Django 5.0.3 on 2026-02-26 20:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("warbands", "0011_warbandlog_parent_warbandtrade_parent"),
        ("warbands", "0012_armour_save_allow_negative"),
    ]

    operations = []
