# Generated by Django 5.0.3 on 2026-02-10 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('type', models.CharField(db_index=True, max_length=80)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
                ('dc', models.CharField(blank=True, default='', max_length=40)),
                ('roll', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spells', to='campaigns.campaign')),
            ],
            options={
                'db_table': 'spell',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SpellCampaignType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spell_links', to='campaigns.campaigntype')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_types', to='spells.spell')),
            ],
            options={
                'db_table': 'spell_campaign_type',
            },
        ),
        migrations.AddConstraint(
            model_name='spellcampaigntype',
            constraint=models.UniqueConstraint(fields=('campaign_type', 'spell'), name='unique_spell_campaign_type'),
        ),
    ]
