# Generated by Django 5.0.3 on 2026-04-04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spells", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spell",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
