# Generated by Django 5.0.3 on 2026-01-25 01:06

import apps.campaigns.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_campaign_types(apps, schema_editor):
    CampaignType = apps.get_model("campaigns", "CampaignType")
    seed_data = [
        {"code": "standard", "name": "Standard"},
        {"code": "mim", "name": "Mutiny in Marienburg"},
    ]
    for entry in seed_data:
        CampaignType.objects.update_or_create(
            code=entry["code"], defaults={"name": entry["name"]}
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'campaign_type',
            },
        ),
        migrations.RunPython(seed_campaign_types, migrations.RunPython.noop),
        migrations.CreateModel(
            name='CampaignRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'campaign_role',
            },
        ),
        migrations.CreateModel(
            name='CampaignPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'campaign_permission',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_type', models.ForeignKey(default=apps.campaigns.models.get_default_campaign_type_id, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='campaigns.campaigntype')),
                ('name', models.CharField(max_length=120)),
                ('join_code', models.CharField(max_length=6, unique=True)),
                ('in_progress', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'campaign',
            },
        ),
        migrations.CreateModel(
            name='CampaignSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='campaigns.campaign')),
                ('max_players', models.PositiveSmallIntegerField(default=8)),
                ('max_heroes', models.PositiveSmallIntegerField(default=6)),
                ('max_hired_swords', models.PositiveSmallIntegerField(default=3)),
                ('max_games', models.PositiveSmallIntegerField(default=10)),
                ('starting_gold', models.PositiveIntegerField(default=500)),
            ],
            options={
                'db_table': 'campaign_settings',
            },
        ),
        migrations.CreateModel(
            name='CampaignHouseRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_rules', to='campaigns.campaign')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'campaign_house_rule',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='campaigns.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_memberships', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='campaigns.campaignrole')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'campaign_membership',
            },
        ),
        migrations.CreateModel(
            name='CampaignMembershipPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='campaigns.campaignmembership')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_permissions', to='campaigns.campaignpermission')),
            ],
            options={
                'db_table': 'campaign_membership_permission',
            },
        ),
        migrations.AddConstraint(
            model_name='campaignrole',
            constraint=models.CheckConstraint(check=models.Q(('slug__in', ['owner', 'admin', 'player'])), name='campaign_role_slug_valid'),
        ),
        migrations.AddConstraint(
            model_name='campaignmembershippermission',
            constraint=models.UniqueConstraint(fields=('membership', 'permission'), name='unique_campaign_membership_permission'),
        ),
        migrations.AddConstraint(
            model_name='campaignmembership',
            constraint=models.UniqueConstraint(fields=('campaign', 'user'), name='unique_campaign_membership'),
        ),
    ]
