# Generated by Django 5.0.3 on 2026-02-17 00:00

import apps.campaigns.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignsettings",
            name="hero_level_thresholds",
            field=models.JSONField(default=apps.campaigns.models.get_default_hero_level_thresholds),
        ),
        migrations.AddField(
            model_name="campaignsettings",
            name="henchmen_level_thresholds",
            field=models.JSONField(default=apps.campaigns.models.get_default_henchmen_level_thresholds),
        ),
        migrations.AddField(
            model_name="campaignsettings",
            name="hired_sword_level_thresholds",
            field=models.JSONField(default=apps.campaigns.models.get_default_henchmen_level_thresholds),
        ),
    ]
