# Generated by Django 5.0.3 on 2026-02-25 14:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("campaigns", "0004_campaignsettings_locations"),
        ("items", "0004_availability_restrictions"),
        ("skills", "0001_initial"),
        ("special", "0001_initial"),
        ("spells", "0001_initial"),
        ("warbands", "0010_warband_restrictions"),
    ]

    operations = [
        migrations.CreateModel(
            name="BestiaryEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "movement",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "weapon_skill",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "ballistic_skill",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "strength",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "toughness",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "wounds",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "initiative",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "attacks",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "leadership",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("type", models.CharField(db_index=True, max_length=80)),
                ("description", models.TextField(blank=True, default="", max_length=4000)),
                ("armour_save", models.CharField(blank=True, default="", max_length=20)),
                ("large", models.BooleanField(default=False)),
                (
                    "caster",
                    models.CharField(
                        choices=[("No", "No"), ("Wizard", "Wizard"), ("Priest", "Priest")], default="No", max_length=20
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bestiary_entries",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "bestiary entries",
                "db_table": "bestiary_entry",
                "ordering": ["type", "name"],
            },
        ),
        migrations.CreateModel(
            name="BestiaryEntryItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "bestiary_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bestiary_entry_items",
                        to="bestiary.bestiaryentry",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bestiary_entry_items",
                        to="items.item",
                    ),
                ),
            ],
            options={
                "db_table": "bestiary_entry_item",
            },
        ),
        migrations.AddField(
            model_name="bestiaryentry",
            name="items",
            field=models.ManyToManyField(
                blank=True, related_name="bestiary_entries", through="bestiary.BestiaryEntryItem", to="items.item"
            ),
        ),
        migrations.CreateModel(
            name="BestiaryEntrySkill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "bestiary_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bestiary_entry_skills",
                        to="bestiary.bestiaryentry",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bestiary_entry_skills",
                        to="skills.skill",
                    ),
                ),
            ],
            options={
                "db_table": "bestiary_entry_skill",
            },
        ),
        migrations.AddField(
            model_name="bestiaryentry",
            name="skills",
            field=models.ManyToManyField(
                blank=True, related_name="bestiary_entries", through="bestiary.BestiaryEntrySkill", to="skills.skill"
            ),
        ),
        migrations.CreateModel(
            name="BestiaryEntrySpecial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "bestiary_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bestiary_entry_specials",
                        to="bestiary.bestiaryentry",
                    ),
                ),
                (
                    "special",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bestiary_entry_specials",
                        to="special.special",
                    ),
                ),
            ],
            options={
                "db_table": "bestiary_entry_special",
            },
        ),
        migrations.AddField(
            model_name="bestiaryentry",
            name="specials",
            field=models.ManyToManyField(
                blank=True,
                related_name="bestiary_entries",
                through="bestiary.BestiaryEntrySpecial",
                to="special.special",
            ),
        ),
        migrations.CreateModel(
            name="BestiaryEntrySpell",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "bestiary_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bestiary_entry_spells",
                        to="bestiary.bestiaryentry",
                    ),
                ),
                (
                    "spell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bestiary_entry_spells",
                        to="spells.spell",
                    ),
                ),
            ],
            options={
                "db_table": "bestiary_entry_spell",
            },
        ),
        migrations.AddField(
            model_name="bestiaryentry",
            name="spells",
            field=models.ManyToManyField(
                blank=True, related_name="bestiary_entries", through="bestiary.BestiaryEntrySpell", to="spells.spell"
            ),
        ),
        migrations.CreateModel(
            name="WarbandBestiaryFavourite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "bestiary_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warband_favourites",
                        to="bestiary.bestiaryentry",
                    ),
                ),
                (
                    "warband",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bestiary_favourites",
                        to="warbands.warband",
                    ),
                ),
            ],
            options={
                "db_table": "warband_bestiary_favourite",
            },
        ),
        migrations.AddConstraint(
            model_name="bestiaryentryitem",
            constraint=models.UniqueConstraint(fields=("bestiary_entry", "item"), name="unique_bestiary_entry_item"),
        ),
        migrations.AddConstraint(
            model_name="bestiaryentry",
            constraint=models.CheckConstraint(
                check=models.Q(("movement__gte", 0), ("movement__lte", 10)), name="bestiary_entry_movement_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="bestiaryentry",
            constraint=models.CheckConstraint(
                check=models.Q(("weapon_skill__gte", 0), ("weapon_skill__lte", 10)),
                name="bestiary_entry_weapon_skill_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="bestiaryentry",
            constraint=models.CheckConstraint(
                check=models.Q(("ballistic_skill__gte", 0), ("ballistic_skill__lte", 10)),
                name="bestiary_entry_ballistic_skill_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="bestiaryentry",
            constraint=models.CheckConstraint(
                check=models.Q(("strength__gte", 0), ("strength__lte", 10)), name="bestiary_entry_strength_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="bestiaryentry",
            constraint=models.CheckConstraint(
                check=models.Q(("toughness__gte", 0), ("toughness__lte", 10)), name="bestiary_entry_toughness_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="bestiaryentry",
            constraint=models.CheckConstraint(
                check=models.Q(("wounds__gte", 0), ("wounds__lte", 10)), name="bestiary_entry_wounds_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="bestiaryentry",
            constraint=models.CheckConstraint(
                check=models.Q(("initiative__gte", 0), ("initiative__lte", 10)), name="bestiary_entry_initiative_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="bestiaryentry",
            constraint=models.CheckConstraint(
                check=models.Q(("attacks__gte", 0), ("attacks__lte", 10)), name="bestiary_entry_attacks_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="bestiaryentry",
            constraint=models.CheckConstraint(
                check=models.Q(("leadership__gte", 0), ("leadership__lte", 10)), name="bestiary_entry_leadership_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="warbandbestiaryfavourite",
            constraint=models.UniqueConstraint(
                fields=("warband", "bestiary_entry"), name="unique_warband_bestiary_favourite"
            ),
        ),
    ]
