# Generated by Django 5.0.3 on 2026-02-26 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0002_hiredswordprofile_hiredswordprofilerestriction_and_more'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiredswordprofile',
            name='available_skill_types',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='HiredSwordProfileAvailableSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hired_sword_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hired_sword_profile_available_skills', to='bestiary.hiredswordprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hired_sword_profile_available_skills', to='skills.skill')),
            ],
            options={
                'db_table': 'hired_sword_profile_available_skill',
            },
        ),
        migrations.AddField(
            model_name='hiredswordprofile',
            name='available_special_skills',
            field=models.ManyToManyField(blank=True, related_name='available_in_hired_sword_profiles', through='bestiary.HiredSwordProfileAvailableSkill', to='skills.skill'),
        ),
        migrations.AddConstraint(
            model_name='hiredswordprofileavailableskill',
            constraint=models.UniqueConstraint(fields=('hired_sword_profile', 'skill'), name='unique_hired_sword_profile_available_skill'),
        ),
    ]
