# Generated by Django 5.0.3 on 2026-01-25 01:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('movement', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('weapon_skill', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('ballistic_skill', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('strength', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('toughness', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('wounds', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('initiative', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('attacks', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('leadership', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races', to='campaigns.campaign')),
            ],
            options={
                'db_table': 'race',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='race',
            constraint=models.UniqueConstraint(fields=('campaign', 'name'), name='unique_campaign_race'),
        ),
        migrations.AddConstraint(
            model_name='race',
            constraint=models.UniqueConstraint(condition=models.Q(('campaign__isnull', True)), fields=('name',), name='unique_global_race_name'),
        ),
        migrations.AddConstraint(
            model_name='race',
            constraint=models.CheckConstraint(check=models.Q(('movement__gte', 0), ('movement__lte', 10)), name='race_movement_range'),
        ),
        migrations.AddConstraint(
            model_name='race',
            constraint=models.CheckConstraint(check=models.Q(('weapon_skill__gte', 0), ('weapon_skill__lte', 10)), name='race_weapon_skill_range'),
        ),
        migrations.AddConstraint(
            model_name='race',
            constraint=models.CheckConstraint(check=models.Q(('ballistic_skill__gte', 0), ('ballistic_skill__lte', 10)), name='race_ballistic_skill_range'),
        ),
        migrations.AddConstraint(
            model_name='race',
            constraint=models.CheckConstraint(check=models.Q(('strength__gte', 0), ('strength__lte', 10)), name='race_strength_range'),
        ),
        migrations.AddConstraint(
            model_name='race',
            constraint=models.CheckConstraint(check=models.Q(('toughness__gte', 0), ('toughness__lte', 10)), name='race_toughness_range'),
        ),
        migrations.AddConstraint(
            model_name='race',
            constraint=models.CheckConstraint(check=models.Q(('wounds__gte', 0), ('wounds__lte', 10)), name='race_wounds_range'),
        ),
        migrations.AddConstraint(
            model_name='race',
            constraint=models.CheckConstraint(check=models.Q(('initiative__gte', 0), ('initiative__lte', 10)), name='race_initiative_range'),
        ),
        migrations.AddConstraint(
            model_name='race',
            constraint=models.CheckConstraint(check=models.Q(('attacks__gte', 0), ('attacks__lte', 10)), name='race_attacks_range'),
        ),
        migrations.AddConstraint(
            model_name='race',
            constraint=models.CheckConstraint(check=models.Q(('leadership__gte', 0), ('leadership__lte', 10)), name='race_leadership_range'),
        ),
    ]
