# Generated by Django 5.0.3 on 2026-01-25 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='campaigns.campaign')),
                ('name', models.CharField(max_length=160)),
                ('type', models.CharField(db_index=True, max_length=80)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
                ('custom', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'skill',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkillCampaignType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_links', to='campaigns.campaigntype')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_types', to='skills.skill')),
            ],
            options={
                'db_table': 'skill_campaign_type',
            },
        ),
        migrations.AddConstraint(
            model_name='skillcampaigntype',
            constraint=models.UniqueConstraint(fields=('campaign_type', 'skill'), name='unique_skill_campaign_type'),
        ),
    ]
