# Generated by Django 5.0.3 on 2026-01-25 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="custom",
        ),
    ]
