# Generated by Django 5.0.3 on 2026-02-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='description',
            field=models.TextField(blank=True, default='', max_length=4000),
        ),
    ]
