# Generated by Django 5.0.3 on 2026-02-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Warband', 'Warband'), ('Warband Group', 'Warband Group'), ('Setting', 'Setting'), ('Artifact', 'Artifact')], default='Warband', max_length=20)),
                ('restriction', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'restriction',
                'ordering': ['type', 'restriction'],
            },
        ),
        migrations.AddConstraint(
            model_name='restriction',
            constraint=models.UniqueConstraint(fields=('type', 'restriction'), name='unique_restriction'),
        ),
    ]
