# Generated by Django 5.0.3 on 2026-02-20 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='traderequest',
            new_name='trade_reque_campaig_c93154_idx',
            old_name='trade_requ_campaign_3a2d2a_idx',
        ),
        migrations.RenameIndex(
            model_name='traderequest',
            new_name='trade_reque_to_user_661eaf_idx',
            old_name='trade_requ_to_user_8f7b46_idx',
        ),
    ]
