# Generated by Django 5.0.3 on 2026-01-25 01:06

from django.core.validators import MaxValueValidator, MinValueValidator
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='campaigns.campaign')),
                ('name', models.CharField(max_length=160)),
                ('type', models.CharField(db_index=True, max_length=80)),
                ('subtype', models.CharField(blank=True, default='', max_length=80)),
                ('grade', models.CharField(default='1a', max_length=2)),
                ('cost', models.PositiveIntegerField(default=0)),
                (
                    'rarity',
                    models.PositiveSmallIntegerField(
                        default=2,
                        validators=[MinValueValidator(2), MaxValueValidator(20)],
                    ),
                ),
                ('unique_to', models.CharField(blank=True, default='', max_length=200)),
                ('variable', models.CharField(blank=True, max_length=120, null=True)),
                ('single_use', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
                ('strength', models.CharField(blank=True, max_length=40, null=True)),
                ('range', models.CharField(blank=True, max_length=40, null=True)),
                ('save_value', models.CharField(blank=True, db_column='save', max_length=40, null=True)),
                ('statblock', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'item',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ItemCampaignType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_links', to='campaigns.campaigntype')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_types', to='items.item')),
            ],
            options={
                'db_table': 'item_campaign_type',
            },
        ),
        migrations.CreateModel(
            name='ItemProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_properties', to='campaigns.campaign')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
            ],
            options={
                'db_table': 'item_property',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemPropertyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_links', to='items.item')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_links', to='items.itemproperty')),
            ],
            options={
                'db_table': 'item_property_link',
            },
        ),
        migrations.AddConstraint(
            model_name='itemcampaigntype',
            constraint=models.UniqueConstraint(fields=('campaign_type', 'item'), name='unique_item_campaign_type'),
        ),
        migrations.AddConstraint(
            model_name='itempropertylink',
            constraint=models.UniqueConstraint(fields=('item', 'property'), name='unique_item_property_link'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(
                check=models.Q(rarity__gte=2, rarity__lte=20),
                name='item_rarity_range',
            ),
        ),
    ]
