# Generated by Django 5.0.3 on 2026-01-25 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('type', models.CharField(db_index=True, max_length=80)),
                ('cost', models.PositiveIntegerField(default=0)),
                ('rarity', models.PositiveSmallIntegerField(default=0)),
                ('unique_to', models.CharField(blank=True, default='', max_length=200)),
                ('variable', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
                ('custom', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='campaigns.campaign')),
            ],
            options={
                'db_table': 'item',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ItemCampaignType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_links', to='campaigns.campaigntype')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_types', to='items.item')),
            ],
            options={
                'db_table': 'item_campaign_type',
            },
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('campaign', 'name'), name='unique_campaign_item_name'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('campaign__isnull', True)), fields=('name',), name='unique_global_item_name'),
        ),
        migrations.AddConstraint(
            model_name='itemcampaigntype',
            constraint=models.UniqueConstraint(fields=('campaign_type', 'item'), name='unique_item_campaign_type'),
        ),
    ]
