# Generated by Django 5.0.3 on 2026-01-25 12:45

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


def clamp_item_rarity(apps, schema_editor):
    Item = apps.get_model("items", "Item")
    Item.objects.filter(rarity__lt=2).update(rarity=2)
    Item.objects.filter(rarity__gt=20).update(rarity=20)


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(clamp_item_rarity, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="item",
            name="rarity",
            field=models.PositiveSmallIntegerField(
                default=2, validators=[MinValueValidator(2), MaxValueValidator(20)]
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                check=models.Q(rarity__gte=2, rarity__lte=20),
                name="item_rarity_range",
            ),
        ),
    ]
