# Generated by Django 5.0.3 on 2026-02-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_update_item_lengths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
