# Generated by Django 5.0.3 on 2026-02-25 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bestiary", "0001_initial"),
        ("items", "0004_availability_restrictions"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="bestiary_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shop_items",
                to="bestiary.bestiaryentry",
            ),
        ),
    ]
